"""Rendering a ledger as the human-readable parity document.

This is what replaces hand-written files like raven-toolbox's
`docs/reference/matlab_raven_backports.md` --- same content, but generated, so it cannot
drift away from the code the way prose does.
"""

from __future__ import annotations

from parity.check import CheckResult
from parity.ledger import Entry, Ledger

_STATUS_TITLES = {
    "python-pending": "Port queue --- MATLAB has it, Python does not",
    "matlab-pending": "Back-port queue --- Python has it, MATLAB does not",
    "matlab-only": "Deliberately MATLAB-only",
    "python-only": "Deliberately Python-only",
    "via-dependency": "Covered by a dependency on the other side",
    "unreviewed": "Awaiting triage",
}


def _issue_link(issue: str | None) -> str:
    if not issue:
        return "--"
    if issue.startswith(("http://", "https://")):
        return f"[link]({issue})"
    if "#" in issue:
        repo, _, number = issue.partition("#")
        if repo:
            return f"[{issue}](https://github.com/{repo}/issues/{number})"
    return issue


def _cell(value: str | None) -> str:
    return f"`{value}`" if value else "--"


def _table(entries: list[Entry], columns: tuple[str, ...]) -> list[str]:
    lines = ["| " + " | ".join(columns) + " |", "|" + "|".join("---" for _ in columns) + "|"]
    for entry in sorted(entries, key=lambda e: e.sort_key):
        row = []
        for column in columns:
            if column == "MATLAB":
                row.append(_cell(entry.matlab))
            elif column == "Python":
                row.append(_cell(entry.python))
            elif column == "Issue":
                row.append(_issue_link(entry.issue))
            elif column == "Reason":
                row.append(entry.reason or entry.notes or "--")
            elif column == "Notes":
                row.append(entry.notes or "--")
        lines.append("| " + " | ".join(row) + " |")
    return lines


def render(ledger: Ledger, result: CheckResult | None = None) -> str:
    """Produce the Markdown parity report for a pair."""
    counts = ledger.counts()
    total = len(ledger.entries)

    lines: list[str] = [
        f"# Parity: {ledger.matlab_repo} <-> {ledger.python_repo}",
        "",
        "<!-- Generated by `parity report`. Edit `{}` instead. -->".format(
            ledger.path.name if ledger.path else "the ledger"
        ),
        "",
        "## Summary",
        "",
        "| Status | Count | Share |",
        "|---|---:|---:|",
    ]
    for status, count in counts.items():
        share = f"{100 * count / total:.0f}%" if total else "--"
        lines.append(f"| `{status}` | {count} | {share} |")
    lines += [f"| **total** | **{total}** | |", ""]

    if result is not None:
        errors, warnings = len(result.errors), len(result.warnings)
        verdict = "clean" if not errors else f"**{errors} error(s)**"
        lines += [f"Ledger check: {verdict}, {warnings} warning(s).", ""]

    for status, title in _STATUS_TITLES.items():
        entries = ledger.with_status(status)
        if not entries:
            continue
        lines += [f"## {title}", "", f"{len(entries)} function(s).", ""]
        if status in ("python-pending", "matlab-pending"):
            lines += _table(entries, ("MATLAB", "Python", "Issue", "Notes"))
        elif status == "unreviewed":
            lines += _table(entries, ("MATLAB", "Python", "Notes"))
        else:
            lines += _table(entries, ("MATLAB", "Python", "Reason"))
        lines.append("")

    covered = ledger.with_status("parity")
    lines += [
        "## At parity",
        "",
        f"{len(covered)} function(s) implemented on both sides.",
        "",
    ]
    validated = [e for e in covered if e.scenarios]
    lines += [
        f"{len(validated)} of them are covered by a cross-implementation scenario "
        f"(`parity run` / `parity compare`).",
        "",
    ]
    if covered:
        lines += _table(covered, ("MATLAB", "Python", "Notes"))
        lines.append("")

    return "\n".join(lines)


def render_check(result: CheckResult, strict: bool = False, revisions: tuple[str, str] | None = None) -> str:
    """Produce the terminal summary of a `parity check` run."""
    lines = [f"pair: {result.pair}"]
    if revisions:
        lines.append(f"  matlab: {revisions[0]}")
        lines.append(f"  python: {revisions[1]}")
    lines.append(
        f"scanned: {len(result.inventory.matlab)} MATLAB functions, "
        f"{len(result.inventory.python)} Python exports"
    )
    lines.append(f"ledger:  {len(result.ledger.entries)} entries")

    counts: dict[str, int] = {}
    for finding in result.findings:
        counts[finding.kind] = counts.get(finding.kind, 0) + 1

    if result.findings:
        lines.append("")
        for finding in result.findings:
            lines.append(finding.format())

    lines.append("")
    summary = ", ".join(f"{count} {kind}" for kind, count in sorted(counts.items())) or "nothing to report"
    lines.append(f"findings: {summary}")
    lines.append(f"result:   {'PASS' if result.ok(strict=strict) else 'FAIL'}")
    return "\n".join(lines)
