classdef YeastGEMAdapterParity < YeastGEMAdapter
% YeastGEMAdapterParity  YeastGEMAdapter, redirected to this scenario's own PhylDist.mat.
%
% YeastGEMAdapter.m does not override getPhylDistStructPath, so it inherits the base
% ModelAdapter default: <RAVEN root>/external/kegg/keggPhylDist.mat. That file is a real
% KEGG taxonomy artefact (per RAVEN's getPhylDist.m: "generated by the raven-toolbox
% Python package and distributed as a raven-data release asset"), not something this
% repo vendors or downloads --- fuzzyKcatMatching cannot run against yeast-GEM without
% it. find_inKEGG (fuzzyKcatMatching.m) already degrades gracefully when the model's own
% organism is not found in phylDistStruct.names (falls back to a wildcard '*' match), so
% a small, purpose-built two-organism stand-in is enough to exercise the same code path
% real KEGG data would, without needing that external asset. Two organisms rather than
% one for the same reason kcat_chain_ectestgem's own PhylDist.mat fixture uses two: a
% 1x1 numeric distMat risks being squeezed to a 0-d array by scipy.io.loadmat on the
% Python side (confirmed by direct execution --- IndexError: too many indices for array).
    methods
        function x = getPhylDistStructPath(obj)
            [scenarioDir, ~, ~] = fileparts(mfilename('fullpath'));
            x = fullfile(scenarioDir, 'PhylDist.mat');
        end
    end
end
