"""Render the nightly parity report from the scenario result files.

The nightly job runs every scenario against both implementations and leaves the
raw JSON in ``results/``. This turns that into one page a human will actually
read, and into the state file the next night compares against.

Run as::

    python scripts/nightly_report.py --state nightly/state.json \
        --report nightly/report.md --sha raven.matlab=abc123 ...

Exits 1 if any scenario differs, so the job goes red on real drift rather than
only on a crash.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from parity.config import load_config  # noqa: E402
from parity.scenarios import compare_results, list_scenarios, load_scenario  # noqa: E402

# Enough of a difference list to see what broke; the artefacts hold the rest.
MAX_SHOWN = 10


def _verdict(directory: Path, results: Path) -> tuple[str, list, str]:
    """Compare one scenario's two result files. Returns (verdict, differences, note)."""
    scenario = load_scenario(directory)
    left = results / "python" / f"{scenario.id}.json"
    right = results / "matlab" / f"{scenario.id}.json"

    missing = [side for side, path in (("python", left), ("matlab", right)) if not path.is_file()]
    if missing:
        # A scenario that failed to run is not a match. Saying "no differences"
        # here would be the single most misleading thing this report could do.
        return "ERROR", [], f"no result from {' and '.join(missing)}"

    differences = compare_results(
        json.loads(left.read_text(encoding="utf-8")),
        json.loads(right.read_text(encoding="utf-8")),
        scenario.tolerance,
    )
    return ("MATCH" if not differences else "DIFFER"), differences, ""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pair", default="raven")
    parser.add_argument("--results", default="results")
    parser.add_argument("--state", default="nightly/state.json")
    parser.add_argument("--report", default="nightly/report.md")
    parser.add_argument("--run-url", default="", help="link back to the workflow run")
    parser.add_argument("--stamp", default="", help="UTC date of the run, YYYY-MM-DD")
    parser.add_argument(
        "--sha",
        action="append",
        default=[],
        metavar="pair.side=sha",
        help="revision each side was compared at; repeatable",
    )
    args = parser.parse_args(argv)

    config = load_config()
    results = Path(args.results)
    revisions = dict(item.split("=", 1) for item in args.sha)

    rows = []
    for scenario in list_scenarios(config.root / "scenarios", args.pair):
        verdict, differences, note = _verdict(config.root / "scenarios" / scenario.id, results)
        rows.append((scenario, verdict, differences, note))

    clean = all(verdict == "MATCH" for _, verdict, _, _ in rows)

    lines = [
        "# Nightly parity report",
        "",
        "Generated by the `nightly` workflow; do not edit by hand.",
        "",
        f"- run: {args.stamp or 'unknown date'}"
        + (f" ([workflow run]({args.run_url}))" if args.run_url else ""),
    ]
    for key in sorted(revisions):
        pair_name, side = key.split(".", 1)
        repo = getattr(config.pair(pair_name), side)
        lines.append(f"- {repo.repo} @ `{repo.ref}` &mdash; `{revisions[key][:12]}`")
    lines += ["", "| Scenario | Result | Detail |", "|---|---|---|"]

    if not rows:
        lines.append("| _no scenarios defined_ | &mdash; | &mdash; |")
    for scenario, verdict, differences, note in rows:
        detail = note or (
            "&mdash;" if verdict == "MATCH" else f"{len(differences)} difference(s)"
        )
        lines.append(f"| `{scenario.id}` | {verdict} | {detail} |")

    for scenario, verdict, differences, _ in rows:
        if verdict != "DIFFER":
            continue
        lines += ["", f"## `{scenario.id}`", "", "```"]
        for difference in differences[:MAX_SHOWN]:
            lines.append(difference.format())
        if len(differences) > MAX_SHOWN:
            lines.append(f"  ... and {len(differences) - MAX_SHOWN} more")
        lines.append("```")

    if clean and rows:
        lines += ["", "Both implementations agree on every scenario."]

    report = Path(args.report)
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text("\n".join(lines) + "\n", encoding="utf-8")

    state = Path(args.state)
    state.parent.mkdir(parents=True, exist_ok=True)
    state.write_text(
        json.dumps(
            {
                "revisions": revisions,
                "verdicts": {scenario.id: verdict for scenario, verdict, _, _ in rows},
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )

    print(f"{sum(1 for _, v, _, _ in rows if v == 'MATCH')}/{len(rows)} scenarios match")
    return 0 if clean else 1


if __name__ == "__main__":
    raise SystemExit(main())
